/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}', './public/**/*.html'],
    theme: {
        extend: {
            fontSize: {
                xs: ['0.75rem', { lineHeight: '1rem', letterSpacing: '-0.01em' }],
                sm: ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '-0.01em' }],
                base: ['1rem', { lineHeight: '1.5rem', letterSpacing: '-0.01em' }],
                lg: ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em' }],
                xl: ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '2xl': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '3xl': ['1.875rem', { lineHeight: '2.25rem', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '4xl': ['2.25rem', { lineHeight: '2.5rem', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '5xl': ['3rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '6xl': ['3.75rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '7xl': ['4.5rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '8xl': ['5.25rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: 'bold' }],
                '9xl': ['6rem', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: 'bold' }],
            },
            fontFamily: {
                heading: ['Poppins', 'sans-serif'],
                paragraph: ['Poppins', 'sans-serif'],
                display: ["'Bebas Neue'", 'cursive'],
            },
            colors: {
                primary: '#FF6600',
                'primary-foreground': '#FFFFFF',
                secondary: '#F5F5F5',
                'secondary-foreground': '#1A1A1A',
                accent: '#E55A00',
                'accent-foreground': '#FFFFFF',
                background: '#FFFFFF',
                foreground: '#1A1A1A',
                muted: '#F5F5F5',
                'muted-foreground': '#6B7280',
                card: '#FFFFFF',
                'card-foreground': '#1A1A1A',
                border: '#E5E7EB',
                link: '#FF6600',
                destructive: '#DC2626',
                'destructive-foreground': '#FFFFFF',
                'brand-black': '#000000',
                'brand-orange': '#FF6600',
                'brand-orange-hover': '#E55A00',
                'brand-white': '#FFFFFF',
            },
        },
    },
    future: {
        hoverOnlyWhenSupported: true,
    },
    plugins: [require('@tailwindcss/container-queries'), require('@tailwindcss/typography')],
}
